### ISSUE TITLE
Mail Manager can only handle 1 attachment at a time

### ISSUE THREAD

**Issue by hachichaud** [ToucanToco/tc_mailmanager#1]
In the email attributes, Attachments should be an array so that multiple attachments are possible.
Not really a problem right now, but will be at some point

See: https://github.com/ToucanToco/tc_mailmanager/blob/master/tc_mailmanager/mail_manager.py#L90

From the SendGrid API v3 doc, attachments is an array of object https://sendgrid.com/docs/API_Reference/api_v3.html

**Comment by fspot** [comment]
fixed by https://github.com/ToucanToco/tc_mailmanager/pull/2
